# Keyboard Layout
Keyboard=Romaja
# Auto Reorder
AutoReorder=True
# Word Commit
WordCommit=True
# Hanja Mode
HanjaMode=False

[HanjaModeToggleKey]
0=Hangul_Hanja
1=F9

[PrevPage]
0=Up
1=bracketleft

[NextPage]
0=Down
1=bracketright

[PrevCandidate]
0=Shift+Tab

[NextCandidate]
0=Tab

