version = 1

[global]
dll = "/home/glaumar/Games/SteamLibrary/steamapps/common/Lossless Scaling/Lossless.dll"

[[game]]
exe = ".haruna-wrapped"
multiplier = 2
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "benchmark"
multiplier = 2
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "mpv"
multiplier = 2
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"
