# https://github.com/tomasklaen/uosc/releases/latest/download/uosc.conf

# add memo buton to uosc contrals
controls=menu,gap,<video,audio>subtitles,<has_many_audio>audio,<has_many_video>video,<has_many_edition>editions,<stream>stream-quality,gap,command:history:script-binding memo-history?History,gap,space,<video,audio>speed,space,shuffle,loop-playlist,loop-file,gap,prev,items,next,gap,fullscreen

opacity=timeline=0.5,title=0.5,tooltip=0.5,menu=0.5,submenu=0.4,slider=0.5,slider_gauge=0.8,speed=0.5,thumbnail=0.5

# auto play next file
autoload=yes

timeline_style=line
timeline_line_width=10
timeline_size=25

window_border_size=0
progress=never
