Alt+1 set window-scale 1
Alt+2 multiply window-scale 0.75
Alt+3 multiply window-scale 1.5

Alt+j cycle secondary-sid
Alt+J cycle secondary-sid down

# memo
# https://github.com/po5/memo
h script-binding memo-history

# uosc
# https://github.com/tomasklaen/uosc
> script-binding uosc/next; script-message-to uosc flash-elements top_bar,timeline
< script-binding uosc/prev; script-message-to uosc flash-elements top_bar,timeline
M script-binding uosc/menu; 