# Optimized shaders for higher-end GPU: Mode A (HQ)
no-border
save-position-on-quit
# Anime4K
glsl-shaders="~~/shaders/Anime4K/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K/Anime4K_Restore_CNN_VL.glsl:~~/shaders/Anime4K/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K/Anime4K_Upscale_CNN_x2_M.glsl"

