user_passwd: ENC[AES256_GCM,data:mBFeOUHJm7jeNRS6+UdsaPZBbNCBkWrHyH378nPESCUuLw5GxpWJTLscjShGj+Tpr2TtiWTbMyOtrD6Zq0UIUtoQSOKDddN9UQ==,iv:Axxd9QOwE2ZfuZD6ovPYdgXACw1eVgMzb2bPruYv8Xg=,tag:I4LRwKQKzp4XteRnp00IrQ==,type:str]
samba_passwd: ENC[AES256_GCM,data:/YGiLl0gH1QHHO8=,iv:xLCwHRykKErYWnR0N/cUKuLHWOvCbR19xsOuY9Bg9XE=,tag:pSSkhcfniNRXrp9FnoRUDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gzhu5k0k5r3xveyde4l3edatpf9zx2rwyu4j6v3yy3gegaj2s9sf9y29v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZXMrb2NqdDFYQmFzc2k0
            VklKUTBUNlB0OEs0alBaZDVNWjlYRnRvalNFCjcrcVA2VXcrS0RwejREbDdicXB3
            RGRoN0J1WGIreHJ5UXovdzN4SkE5aEUKLS0tIE9BVFgrdERGK1VBRzcva0MvWmRD
            dDdsVkNVbjRlV1VvWlBNV3BVZTZtS2sKU58PaEiHNp1TV5+iskh8EFwJQ6DDyfBi
            HEHQ7cN+Wz8VHS6BQf2nMoD1mLNVbOx3f0nOLa3rmEB2Fyn4BX34kg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j55px5k0hl49w59g57ya77dt5h02vj5deqnjusk8uz852jc6e5xqdwgd5x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWVhVMzBldTNMaGloUUR0
            bE05amRVa1hNTjhJWitZMnNUdDUwWmFpb2dJCnIvYldsMG9jeklNRWtCcEtRZG9o
            UmhSeWtwZjJNUWM3eXB2SzJFSGJaVDgKLS0tIDVxMzg4dFVWdkRIblpsdGNyWGR2
            dmNqNXlOWTdFK2g4dWpPb0txekkzelUK/vL7s3SRd/wIRy5RF+D0gbulX7rTMxnB
            Dmjf/41FC9ZIo5WUxYoAjCMPRTZGy0uHCQAsV1KflVHP25BaM6xgCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T19:54:47Z"
    mac: ENC[AES256_GCM,data:HQg0EDSeFZNmHHggIpEKKzYPRfblvE+kUMz1Rcv4i53Z3bUY9OOcZPVC+yZITVp7cEhpfGI9nWsrYOsYhkovsibXbe8dJmc+V0yD//F6l2v5KSq5szCCuRaISEBb9lP0V9lmjDnjLNSSBz+QlKpJMMpxIohUYAL+oX+4ABQktko=,iv:GsRxxAW04iJlWqutu982i9wHZ21qW3hgGfMiTjkX/yA=,tag:gCAZitnDhMMUzBiUZlT5oQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
