user_passwd: ENC[AES256_GCM,data:kFlOzHWII09Ccq+gqEibToF6pXpLcvgSn4jfC04UTZ9prcLBv651IVLBuLSNpOezW2N9pSTjBuIdkrob2GvFaDOc0q3Tc/j2Rg==,iv:8+4xD1dUZW3tlgLoZK3qDQeVhzKLmU569iEPa6eQ0cw=,tag:W9z7pIEFsu2dRELrVwyRuQ==,type:str]
samba_passwd: ENC[AES256_GCM,data:Aci8FNfFhfKRu0M=,iv:WcJd98wqi/a200f0PhwDrWkl7iyWRrqbxWNiV9H1sYg=,tag:5Z5L8wnsu70+KY8dtvRxFA==,type:str]
ssh_passphrase: ENC[AES256_GCM,data:/yfxbwuEQpOq56Y=,iv:fAVX5ZqIHrMVg/bdCdJnUkDsX+rCZdpT2M8bpQpcess=,tag:OKDLdY30h45OMX9d40FYQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5cckmfesmvf8u0h8q2wpyzym4x7fzwak0kn7t5ryqxf0kd54a2shh0ly4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OG5aSE5BckIvZExYcTFB
            ZlQvdk0zQXoxZTFpcmVWQ0NlOGJDNTBMRFdBCnF3K3h6N0t6TzhVd0RmakZ5ZzRh
            bFlHWmR6V2NKaG9RNVcvTVZwTUJrWDQKLS0tIHl3VmlRVzMzVVZ5S09XU0dDb3hi
            NGN2UnZEcVZkMXJlcjlJby9ld3FPYTgKM75MCG4IHT2NqZ3wm/R2tExlY4sKkzy3
            PRdBEGGOTo3mHt+gs9N9MS9ffqEqHkGghYLpPD2q6x4ompIGEU94cw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j55px5k0hl49w59g57ya77dt5h02vj5deqnjusk8uz852jc6e5xqdwgd5x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVkFjYytDbWR4VFkwMVMr
            Sm42L0gwYWtxdlVLaU1sR0hkYm9GV05KVzJRCm9paVo2MzA3d3pFbzYyaE4zT1hu
            TWRNdTVwa25OYjV6WkZFYlh2S2UxaWcKLS0tIHF2aEV3aFdOZC9XWGdQTVV0am15
            L09IbGU0NjVpNXRLSVZlNkhlZDIzRk0KiKttpPdKB1aVuzBcqXt8aM8x/9CTop5F
            IdCNCNv8c+7nE5TG7KEfLQvNQtBRiLg7IGLlg2AMQUVlcpryUVOHbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eaxt06lu4h8cr2m6dgvlgzfg3amaqw9qdeynhs4nsfaum4nxz4tqm54dnt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQmdsZEkxczlGSWxUa0Nr
            MjhaclVlaTVZdWM5VkVYK0dvZzhHTkJSRm5RCm56aTdwTGRmZVVReXMvWER3TmYz
            WDMvdzFLeFVtS29jNVlGN1lkYnZ6VVkKLS0tIHpvYnZGL3doYW9wNlFtRi90aTdl
            QitJMjZ4Y3RxOUVxSUowTmwvRTFMQnMKB3eOknilysEhRRuPJMP5n7TmkTlskBz9
            FnztkDzkWV3RnzBRLx+DCdm0JbEEuNvd9Wje6vVD7IaSvo5o0MPdOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T23:03:36Z"
    mac: ENC[AES256_GCM,data:2ij0ENu/xyZhcx6mT0LleFTVvTQsC5bxDEkEg6ukxG2MuuybsFuNbA9KBzPG2RczMImV54udV0MhB6iqxTg9nsRP/G/38X39Lme1y2LwZ2MX3lt9MDBBc/WXcYOguZHAqxBlvGOKEmRgOhZo9hBkCp3td1154uCMDUS4r5GQTIs=,iv:609fkF8UlJC7bE0OgTPqCOvqfEwmUU7hq0XDtxUeD2Y=,tag:+3qcXkRRSlpoxmBvj+gEkg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
