user_passwd: ENC[AES256_GCM,data:kFlOzHWII09Ccq+gqEibToF6pXpLcvgSn4jfC04UTZ9prcLBv651IVLBuLSNpOezW2N9pSTjBuIdkrob2GvFaDOc0q3Tc/j2Rg==,iv:8+4xD1dUZW3tlgLoZK3qDQeVhzKLmU569iEPa6eQ0cw=,tag:W9z7pIEFsu2dRELrVwyRuQ==,type:str]
samba_passwd: ENC[AES256_GCM,data:Aci8FNfFhfKRu0M=,iv:WcJd98wqi/a200f0PhwDrWkl7iyWRrqbxWNiV9H1sYg=,tag:5Z5L8wnsu70+KY8dtvRxFA==,type:str]
ssh_passphrase: ENC[AES256_GCM,data:/yfxbwuEQpOq56Y=,iv:fAVX5ZqIHrMVg/bdCdJnUkDsX+rCZdpT2M8bpQpcess=,tag:OKDLdY30h45OMX9d40FYQg==,type:str]
nextcloud_passwd: ENC[AES256_GCM,data:UrNZ9epb6RsTMndvZVu3YqEozSu9czI=,iv:QFL8boGhX8+xOomplrhkWb41m4hcNIjwFCstLo2TZSA=,tag:+XvfXB1B07Vsvk7NA6+3eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5cckmfesmvf8u0h8q2wpyzym4x7fzwak0kn7t5ryqxf0kd54a2shh0ly4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NWdVNTRCZTVPYmlWaTA4
            V1krajlidnVrR251TWtha2wzb1U4Vjh3NndzCnhwbHhLMVZRbytwTGt0QzMyZ2Zw
            NGhXcDRkS1N0NmFsVVpFR0V1WEFRYVEKLS0tIFMzQmJwNFdWRVJ3R2VCSHZnNWF4
            WkR3SFFvZmQyTlpxclBFbWVkd1NrZDAK16PuuPCgwk0b2M8H15QyuXdy9j5YAtby
            J8ConVgNRn1CwrA5jbSYgvcXFxjCEuXCLz0cyyOw9E9hTRZCYD6xDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j55px5k0hl49w59g57ya77dt5h02vj5deqnjusk8uz852jc6e5xqdwgd5x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidGptTkNTWjdodWM4RHA1
            Rkh6Y29Ed3VMaHBnOVlzTTJYSm9QUGFkY25rClVvU3JiZ29ra1NVbjl4LzM4V2VC
            ZEhTMlVJdWcyUFBKS0g2akRxTXVPWncKLS0tIHFlbXNPV3FTMnJXZFRCZ1RseDFU
            NjZHQjIrTE94NDR3d3ViZVdJNmVTaU0K/QmBZF5AtnXYmQ5+yQIM/wafgeLcHWKN
            Y9j/dQbB1g0SEthwQuhcBI94lqP2sr8w8qJBveqcIYjYTxW+zc5DVw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1svk4xm4harkcj7636j54fndjsqz60xftpe9ju4p37xsd6e6rw4hsqwt46z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UjNhUVFzelpoaThtb3lv
            LzVQa09qZ1ZpblZNbk9xWDl5ZmFEeUN5R1JjCkphd0hSY3ZYeGFJZkZzckJISk1B
            MnBmR200WEZod0NFQkRBdHpjTEJYOWcKLS0tIDRhZFdvb0FWSjFvNzRuaEh0NXVK
            ZW5JSTlsZE1RZURuTnFlVkVGUXBMRVkKJZ8yTZILr4M55nub7sJUDLg3ujEq9ZTH
            AKzEnQhJFPDckS99MtgHV/wWJhTF9kjz/nKQ4QLixymhJqPb/NCS7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eaxt06lu4h8cr2m6dgvlgzfg3amaqw9qdeynhs4nsfaum4nxz4tqm54dnt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZWFFMmxLYUI1Wlc1WENh
            ZTZOMVI5VkdpSVAvYkdlUlNzN1FwQkRpUTBVCnNuaDZhMFlPbWsxT2hlM2JXUENY
            Zmk2NEhmWHRuZ01laDRQbVdZeWlNRncKLS0tIGlCT3hJL3FqYUJ1dTZ5R2hVelha
            U1V3MGoxMGUxSjdNcGxuM3Z2aWxjZEUKXnDSZH4cgJGI92wVUsbssSkRwsqiXAgE
            k+q9VCGdwjMWoB7stsiIm9L8Xz8UNzjmFUepWnSaY0SrDaH/JJT7GA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-11T11:39:36Z"
    mac: ENC[AES256_GCM,data:xFVsLFvXay7V9g3oIPDhyxU3z5ERFWxQcFtLo4ugRrXGSTxQzcDbbrCC+VNr81KBTHIHitRGg0+SvV/AL1lB4BHuoxojSLpglKpkArKS1p82N/09ldEg+TTKThDC98W5EbgLRAJALfuGcinVIurjADEqngaCLoNd3LQzihoZRYw=,iv:DGylH+LusCvfR327ZWtn94jIaBqI8CeBHo8KErwYXWI=,tag:LRb/KjMmUrHS4QHufZwSWg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
