user_passwd: ENC[AES256_GCM,data:kFlOzHWII09Ccq+gqEibToF6pXpLcvgSn4jfC04UTZ9prcLBv651IVLBuLSNpOezW2N9pSTjBuIdkrob2GvFaDOc0q3Tc/j2Rg==,iv:8+4xD1dUZW3tlgLoZK3qDQeVhzKLmU569iEPa6eQ0cw=,tag:W9z7pIEFsu2dRELrVwyRuQ==,type:str]
samba_passwd: ENC[AES256_GCM,data:Aci8FNfFhfKRu0M=,iv:WcJd98wqi/a200f0PhwDrWkl7iyWRrqbxWNiV9H1sYg=,tag:5Z5L8wnsu70+KY8dtvRxFA==,type:str]
ssh_passphrase: ENC[AES256_GCM,data:/yfxbwuEQpOq56Y=,iv:fAVX5ZqIHrMVg/bdCdJnUkDsX+rCZdpT2M8bpQpcess=,tag:OKDLdY30h45OMX9d40FYQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOb2JFT2xwRGM2TWk1Tkty
            NmVsRWhJSU5vVzBVb3F6Tm1taHJMVVBIc0FjCjNQYlh5dUlGdDlKSmt0ZXk2S1Yz
            S2tpU2xQRmF3WU9iV1puOHlHRVZLOWMKLS0tIGppL05SbFVHcHJ6NUN2NHhpSUI1
            RytxSVZFZGJyRWlLby9mUFduc1RuNUEKoKXTrobGAoEfzyQKtEPkWw9jHEU0FzEf
            HXa+Xrg1M/mDlI1iqg2sgFoluW1NQSfE/tnzQoZdcrTx01xd2oZxGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eaxt06lu4h8cr2m6dgvlgzfg3amaqw9qdeynhs4nsfaum4nxz4tqm54dnt
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK2RCK0dkRWdFTTdRRmtm
            RThkM1ZlK3Z1T2tycVFOQzJkb2hYaldnS0NJCm43UytCUWw5eENEb3p5QkdKMDZX
            cE5JYndlZWhHL3ptc1NZTktYeGtFdEUKLS0tIEpKNHdWaW5hVm0zcEJGbWJCRHE5
            T2crNllJbzhrWTJHSmE5dy9lY0hZOVUKonds4jlL7SMuhybSp5w+L8TXR/yj14+o
            zMbobAnBejbz/5EnoABoH+xe5uRj3Ucx6AFrASCjHcymdy4LeirNag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18hjs9j7kxfkc8uxw0hu3sms5n2ndva7dwxs8s678r5lrmkyhwe7spplwfc
    lastmodified: "2026-09-14T06:11:52Z"
    mac: ENC[AES256_GCM,data:6s5PtgOFBgS8O4xubDjiiO2Q8Vjmng6GspKfPZUjRdENZwu2OgV/MMvIwazol9e8FzR5rqDEUnA2sNl3hfrMkPHWZ27I0vAAuGW/Ba8se8o0dD0GRXrBIIHYv85jtZdn5M0LCKdTBtx7+kLXziB50BFDEucRZYHFlb8twiOmRwE=,iv:utfoua1wf91RZI71/UH+o0g4vvgzro12jxTkuW0WJx4=,tag:VlHHYMWfftlItGtSIeu1Xg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
