user_passwd: ENC[AES256_GCM,data:kFlOzHWII09Ccq+gqEibToF6pXpLcvgSn4jfC04UTZ9prcLBv651IVLBuLSNpOezW2N9pSTjBuIdkrob2GvFaDOc0q3Tc/j2Rg==,iv:8+4xD1dUZW3tlgLoZK3qDQeVhzKLmU569iEPa6eQ0cw=,tag:W9z7pIEFsu2dRELrVwyRuQ==,type:str]
samba_passwd: ENC[AES256_GCM,data:Aci8FNfFhfKRu0M=,iv:WcJd98wqi/a200f0PhwDrWkl7iyWRrqbxWNiV9H1sYg=,tag:5Z5L8wnsu70+KY8dtvRxFA==,type:str]
ssh_passphrase: ENC[AES256_GCM,data:/yfxbwuEQpOq56Y=,iv:fAVX5ZqIHrMVg/bdCdJnUkDsX+rCZdpT2M8bpQpcess=,tag:OKDLdY30h45OMX9d40FYQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5cckmfesmvf8u0h8q2wpyzym4x7fzwak0kn7t5ryqxf0kd54a2shh0ly4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YXU1bXpvSnJrbXoyM2R2
            QVFMVWRMVm45d21OUGJNWWRLd0UxTDIzZFhzCjl1Z1o2eHZKdWMxNk5rbUtTVGR2
            dUh2dmRoN0ZuMWJuNTB6SC83MGg1b28KLS0tIFNYMHFOTGtteTVVQ2V3dHZBZWdL
            cWpDYjNIWDhlTmxRcTZoczBZczlNWFEKR4xaY1GxNULlqJaeosaXi2vVXYDOAYPr
            33KzH7B5kYHGagSLJPcdJINptQSdqaHL+je81WvOMhf7/oLV1zRv5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j55px5k0hl49w59g57ya77dt5h02vj5deqnjusk8uz852jc6e5xqdwgd5x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRnNPU1hCM0pRdlNQWGZN
            WGZQTDk2emZidVltZU1TYnhILzhsNmhxWUZVCjRzeGdKeHpnajlNc3kxbVQrc3c3
            K0p4TDUzU1d2cnZCWjE0TVZQbTZBTjgKLS0tIHNpeDBSMXgzZXdzVHBCeVdIMElL
            bGYwMnFYWWduM3l5OTV4VlVrSkJDVWsKBm1w7HHTtZD3LN7QDDgDz1x2cSsFFYES
            jsYCNUNOM+BhCy3SJVc/uqKwwjck6LnxqmvXLTumim0n2Toq7YO70A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T23:03:36Z"
    mac: ENC[AES256_GCM,data:2ij0ENu/xyZhcx6mT0LleFTVvTQsC5bxDEkEg6ukxG2MuuybsFuNbA9KBzPG2RczMImV54udV0MhB6iqxTg9nsRP/G/38X39Lme1y2LwZ2MX3lt9MDBBc/WXcYOguZHAqxBlvGOKEmRgOhZo9hBkCp3td1154uCMDUS4r5GQTIs=,iv:609fkF8UlJC7bE0OgTPqCOvqfEwmUU7hq0XDtxUeD2Y=,tag:+3qcXkRRSlpoxmBvj+gEkg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
